name: CI

on:
  push:
    branches: [ master ]
jobs:
  publish-nix-bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v6
        with:
          name: nix-bazel
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker image with Nix
        run: nix-build
      - name: Load image into Docker
        run: docker load < result
      - name: Push the latest Docker image
        run: docker push marcop010/nix-bazel:latest